import './globals.css'
import type { Metadata } from 'next'
import { arsenal } from '@/app/fonts'


export const metadata: Metadata = {
  title: 'Cars catalogue',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={arsenal.className}>{children}</body>
    </html>
  )
}
